# The workflow tests the RPP build for OCL backend and runs rpp-performancetests

name: CICD RPP OCL

on:
  pull_request:
    branches: [ ar/workflows ]

jobs:

  build:
    name: Build validation and Performance check
    runs-on: [self-hosted, Linux, X64, cpu-gpu]
    steps:
    - name: Build validation - OCL
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo "PR#$PR_NUMBER is being verified."
        cd ~/dockerMount/abishek/github-workflows
        sudo rm -rf *
        git clone git@github.com:r-abishek/rpp.git
        cd rpp
        git checkout ar/workflows
        git fetch origin pull/$PR_NUMBER/head:ar/pr
        git checkout ar/pr
        git log -3
        sudo docker exec workflows_do_not_use /bin/bash -c "cd /media/abishek/github-workflows/rpp; mkdir build; cd build; cmake -DBACKEND=OCL ..; sudo make -j20 install"
    - name: Performance check - OCL
      run: |
        sudo docker exec workflows_do_not_use /bin/bash -c "cd /media/abishek/github-workflows/rpp/utilities/rpp-performancetests/OCL_NEW; python3 generatePerformanceLogs.py"
    - name: Compatibility check - OCL
      run: |
        echo "PR#$PR_NUMBER is being verified."
        cd ~/dockerMount/abishek/github-workflows
        git clone https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX.git
        cd MIVisionX
        git log -3
        sudo docker exec workflows_do_not_use /bin/bash -c "cd /media/abishek/github-workflows/MIVisionX; mkdir build; cd build; cmake -DBACKEND=OCL ..; sudo make -j20 install"
    - name: Clean up
      run: |
        cd ~/dockerMount/abishek/github-workflows
        sudo rm -rf *